config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions"}
  devise_for :admins, controllers: { sessions: "admins/sessions" }
  resources :vacations
  resources :employees
  resources :users
  resources :admins
  root 'home#index'

  get 'home/index'

end

app/models/vacation.rb
class Vacation < ActiveRecord::Base
  belongs_to :employee
  def state_string
     if state == 0 or state == nil
        return "Waiting for approval"
    elsif state == 1
        return "Approved"
    elsif state == 2
        return "Rejected"
    end
  end
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  #include Devise::Controllers::Helpers
  #before_filter :authenticate_user!
  #verify what type of user is accessing information :w
  before_action :set_vacation, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  #before_filter :ensure_priviliged!

  # GET /vacations
  # GET /vacations.json
  def index
    check_who_logged_in!
    #display only vacations for currently logged in user:
    @employee = Employee.where(user_id: current_user.id)[0]
    if @employee
        @vacations = Vacation.where(employee_id: @employee.id)
    else
        @vacations = nil
    end
    #listing vacation requests waiting for approval in case logged in user is a manager:
    @manager = false
    #if Employee.where(user_id: current_user.id)[0].level == 1
    #if @employee.level == 1
    if @is_manager
        @manager = true
        #find all vacations where employee's manager is current user:
        @subordinates = @employee.subordinates
        #find vacations of all subordinates:
        @subvacations = []
        index = 0 #index of an array to set
        @subordinates.each do |subordinate|
            vac = Vacation.where(employee_id: subordinate.id)
            if vac
                @subvacations[index] = vac
                index += 1
            end
            vac = nil
        end
    end
  end
  # GET /vacations/1
  # GET /vacations/1.json
  def show
    @employee = Employee.where(user_id: current_user.id)[0]
  end

  # GET /vacations/new
  def new
    @employee = Employee.where(user_id: current_user.id)[0]
    @vacation = Vacation.new
  end

  # GET /vacations/1/edit
  def edit
    check_who_logged_in!
    @employee = Employee.where(user_id: current_user.id)[0]
    if not @vacation.state == 0
      redirect_to @vacation, notice: 'You cannot edit once vacation was processed by your manager.'
    end
  end

  # POST /vacations
  # POST /vacations.json
  def create
    check_who_logged_in!
    @vacation = Vacation.new(vacation_params)
    @employee = Employee.where(user_id: current_user.id)
    @vacation.employee_id = @employee[0].id
    @vacation.state = 0

    respond_to do |format|
      if @vacation.save
        format.html { redirect_to @vacation, notice: 'Vacation request was successfully created.' }
        format.json { render :show, status: :created, location: @vacation }
      else
        format.html { render :new }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacations/1
  # PATCH/PUT /vacations/1.json
  def update
    check_who_logged_in!
    respond_to do |format|
      if @vacation.update(vacation_params)
        format.html { redirect_to @vacation, notice: 'Vacation was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacation }
      else
        format.html { render :edit }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacations/1
  # DELETE /vacations/1.json
  def destroy
    check_who_logged_in!
    @vacation.destroy
    respond_to do |format|
      format.html { redirect_to vacations_url, notice: 'Vacation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacation
      @vacation = Vacation.find(params[:id])
      #set @vacation to nil if user is not allowed to see it:
      if not admin_signed_in? and not current_user.is_manager? and not current_user.employee.id == @vacation.employee_id
       @vacation = nil 
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacation_params
      #status can be only updated by managers and admins
      if admin_signed_in? or current_user.is_manager?
        params.require(:vacation).permit(:employee_id, :start_date, :end_date, :employee_comments, :manager_comments, :state)
      else
        params.require(:vacation).permit(:employee_id, :start_date, :end_date, :employee_comments)
      end
    end
    def ensure_priviliged!
      if not admin_signed_in? and current_user and not current_user.is_manager? 
        authenticate_admin!
      elsif not user_signed_in?
        authenticate_admin!
        #return false
      end
    end
    def check_who_logged_in!
      #variables showing who is signed in to pass to the view
      #if not current_user
      #    before_filter :authenticate_user!
      #    #at least user has to be signed in
      #end
      @is_user = false 
      @is_manager = false 
      @is_admin = false 
      @is_priviliged = false
      
      if user_signed_in? and current_user.employee
        @is_user = true
      end
      if current_user and current_user.is_manager?
          @is_priviliged = true
          @is_manager = true
      end
      if admin_signed_in?
          @is_priviliged = true
          @is_admin = false
      end  
    end
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/vacations/_form.html.erb
<%= form_for(@vacation) do |f| %>
  <% if @vacation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vacation.errors.count, "error") %> prohibited this vacation from being saved:</h2>

      <ul>
      <% @vacation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @employee %>
    <p>Editing vacation no <%= @vacation.employee_id %> of <%= @employee.full_name %> </p>
  <%else%>
    <div class="field">
      <%= f.text_field :employee_id %>
    </div>
  <%end%>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :employee_comments %><br>
    <%= f.text_area :employee_comments %>
  </div>
  <div class="field">
    <%= f.label :manager_comments %><br>
    <%if @is_priviliged%>
      <%= f.text_area :manager_comments %>
    <%else%>
      <%= @vacation.manager_comments%>
    <%end%>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%#allow editing only for priviliged users (it's already taken care in controller, just for consistency%>
    <%if @is_priviliged%>
      <%#= f.number_field :state %>
      <%= f.select :state, [["Waiting for approval", 0], ["Approved", 1], ["Rejected", 2]] %>
    <%else%>
      <%= @vacation.state_string%>
    <%end%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vacations/edit.html.erb
<h1>Editing Vacation</h1>

<%= render 'form' %>

<%= link_to 'Show', @vacation %> |
<%= link_to 'Back', vacations_path %>

app/views/vacations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vacations</h1>

<%if @vacations %>
<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Employee comments</th>
      <th>Manager comments</th>
      <th>State</th> 
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vacations.each do |vacation| %>
      <tr>
        <td><%= link_to vacation.employee.full_name, vacation.employee %></td>
        <td><%= vacation.start_date %></td>
        <td><%= vacation.end_date %></td>
        <td><%= vacation.employee_comments %></td>
        <td><%= vacation.manager_comments %></td>
        <td><%= vacation.state_string %></td>
        <td><%= link_to 'Show', vacation %></td>
        <td><%= link_to 'Edit', edit_vacation_path(vacation) %></td>
        <td><%= link_to 'Destroy', vacation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%else%>
    <%#currently logged in user has no vacations to display%>
    <p> You have no vacations to show </p>
<%end%>
<%#listing vacations to approve%>

<%if @manager %>
<%if @vacations %>
  <p> As Manager you have the following vacations to approve: </p>
  <table>
    <thead>
      <tr>
        <th>Employee</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Employee comments</th>
        <th>Your comments as Manager</th>
        <th>State</th> 
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @subvacations.each do |vacations| %>
        <% vacations.each do |vacation| %>
         <tr>
          <td><%= link_to vacation.employee.full_name, vacation.employee %></td>
          <td><%= vacation.start_date %></td>
          <td><%= vacation.end_date %></td>
          <td><%= vacation.employee_comments %></td>
          <td><%= vacation.manager_comments %></td>
          <td><%= vacation.state_string %></td>
          <td><%= link_to 'Show', vacation %></td>
          <td><%= link_to 'Edit', edit_vacation_path(vacation) %></td>
          <td><%= link_to 'Destroy', vacation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%else%>
    <%#currently logged in manager has no vacations to approve%>
    <p> You have no vacations to approve </p>
  <%end%>
<%end%>
<br>

<%= link_to 'New Vacation', new_vacation_path %>

app/views/vacations/new.html.erb
<h1>New Vacation</h1>

<%= render 'form' %>

<%= link_to 'Back', vacations_path %>

app/views/vacations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @vacation.employee %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @vacation.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @vacation.end_date %>
</p>

<p>
  <strong>Employee comments:</strong>
  <%= @vacation.employee_comments %>
</p>

<p>
  <strong>Manager comments:</strong>
  <%= @vacation.manager_comments %>
</p>

<p>
  <strong>State:</strong>
  <%= @vacation.state %>
</p>

<%= link_to 'Edit', edit_vacation_path(@vacation) %> |
<%= link_to 'Back', vacations_path %>