config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions"}
  devise_for :admins, controllers: { sessions: "admins/sessions" }
  resources :vacations
  resources :employees
  resources :users
  resources :admins
  root 'home#index'

  get 'home/index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Welcome to HRonos</h1>

<%#<p>Find me in app/views/home/index.html.erb</p>%>

<% if not user_signed_in? %>
    <p>As it is a HR application allowing users to register themselves is not a good idea, only admin or manager can create new users</p>
    <p>For the presentation purpose there is standard admin account (it's checked in application controller every time the application starts and if there is not such account it's created) :</p>
    <ul>
      <li>Admin account leszek.dubicki@student.ncirl.ie, password: admin123 (unles it was already changed)</li>
    </ul>
    <p> Using this account new users can be added </p>
<% end %>

<%# offer registration for new admin if admin is already signed in %>
<% if admin_signed_in? %>
 <%#= link_to 'Register new admin', new_admin_registration_path %>
 <p><%= link_to 'List administrators', 'admins' %></p>
 <p><%= link_to 'List users', 'users' %></p>
 <p><%= link_to 'List employees', 'employees' %></p>
<% elsif user_signed_in?  and current_user.is_manager?%>
 <%#list everytging except admins list:%>
 <p><%= link_to 'List users', 'users' %></p>
 <p><%= link_to 'List employees', 'employees' %></p>
 <p><%= link_to 'List vacatoins', 'vacations' %></p>
<% elsif user_signed_in?%>
 <%#list only vacations%>
 <p><%= link_to 'List vacatoins', 'vacations' %></p>
<% end %>